PREFIX = "obin:lang:"

NOT = PREFIX + "not"
ELEM = PREFIX + "elem"
IS = PREFIX + "is"
ISNOT = PREFIX + "isnot"
KINDOF = PREFIX + "kindof"
# UTIL FUNCS CALLS TO WHICH GENERATED BY COMPILER
DERIVE = PREFIX + "derive"
IS_INDEXED = PREFIX + "is_indexed"
IS_SEQ = PREFIX + "is_seq"
IS_DICT = PREFIX + "is_dict"
LEN = PREFIX + "len"
TYPE = PREFIX + "deftype"
METHOD = PREFIX + "defmethod"
TRAIT = PREFIX + "deftrait"
IMPLEMENT = PREFIX + "defimplement"
UNION = PREFIX + "defunion"

SLICE = PREFIX + "slice"
DROP = PREFIX + "drop"
TAKE = PREFIX + "take"

AT = PREFIX + "at"
PUT = PREFIX + "put"

REST = PREFIX + "rest"
FIRST = PREFIX + "first"
CONS = PREFIX + "cons"

EQ = PREFIX + "=="
GE = PREFIX + ">="
