PRIM_IS_INDEXED = "___is_indexed"
PRIM_IS_SEQ = "___is_seq"
PRIM_IS_MAP = "___is_map"
PRIM_LENGTH = "___length"
PRIM_IS = "is"
PRIM_ISNOT = "isnot"
PRIM_KINDOF = "kindof"
PRIM_UNION = "___union"
PRIM_TYPE = "___type"
PRIM_METHOD = "___method"
PRIM_TRAIT = "___trait"
PRIM_IMPLEMENT = "___implement"

