PRIM_IS_INDEXED = "obin:lang:is_indexed"
PRIM_IS_SEQ = "obin:lang:is_seq"
PRIM_IS_MAP = "obin:lang:is_map"
PRIM_LENGTH = "obin:lang:length"
PRIM_IS = "is"
PRIM_ISNOT = "isnot"
PRIM_KINDOF = "kindof"
PRIM_UNION = "obin:lang:defunion"
PRIM_TYPE = "obin:lang:deftype"
PRIM_METHOD = "obin:lang:defmethod"
PRIM_TRAIT = "obin:lang:deftrait"
PRIM_IMPLEMENT = "obin:lang:defimplement"

