# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_VOID = 3
NT_INT = 4
NT_FLOAT = 5
NT_STR = 6
NT_MULTI_STR = 7
NT_CHAR = 8
NT_WILDCARD = 9
NT_NAME = 10
NT_TEMPORARY = 11
NT_SYMBOL = 12
NT_TYPE = 13
NT_MAP = 14
NT_LIST = 15
NT_TUPLE = 16
NT_INDEXED = 17
NT_UNIT = 18
NT_CONS = 19
NT_COMMA = 20
NT_CASE = 21
NT_LENSE = 22
NT_LITERAL = 23
NT_FUN = 24
NT_DEF = 25
NT_OVERRIDE = 26
NT_USE = 27
NT_LAMBDA = 28
NT_DISPATCH = 29
NT_FARGS = 30
NT_CONDITION = 31
NT_WHEN = 32
NT_MATCH = 33
NT_TRY = 34
NT_RECEIVE = 35
NT_DECORATOR = 36
NT_MODULE = 37
NT_IMPORT = 38
NT_IMPORT_HIDING = 39
NT_INCLUDE = 40
NT_INCLUDE_HIDING = 41
NT_EXPORT = 42
NT_LOAD = 43
NT_TRAIT = 44
NT_EXTEND = 45
NT_GENERIC = 46
NT_METHOD = 47
NT_INTERFACE = 48
NT_DESCRIBE = 49
NT_BIND = 50
NT_THROW = 51
NT_REST = 52
NT_ASSIGN = 53
NT_ASSIGN_FORCE = 54
NT_CALL = 55
NT_JUXTAPOSITION = 56
NT_UNDEFINE = 57
NT_LOOKUP = 58
NT_IMPORTED_NAME = 59
NT_HEAD = 60
NT_TAIL = 61
NT_DROP = 62
NT_RANGE = 63
NT_MODIFY = 64
NT_OF = 65
NT_IS_IMPLEMENTED = 66
NT_AS = 67
NT_DELAY = 68
NT_LET = 69
NT_NOT = 70
NT_AND = 71
NT_OR = 72
NT_END_EXPR = 73
NT_END = 74
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_VOID", "NT_INT", "NT_FLOAT", "NT_STR", "NT_MULTI_STR", "NT_CHAR",
               "NT_WILDCARD", "NT_NAME", "NT_TEMPORARY", "NT_SYMBOL", "NT_TYPE", "NT_MAP", "NT_LIST", "NT_TUPLE",
               "NT_VECTOR", "NT_UNIT", "NT_CONS", "NT_COMMA", "NT_CASE", "NT_LENSE", "NT_LITERAL", "NT_FUN", "NT_DEF",
               "NT_DEF_PLUS", "NT_USE", "NT_LAMBDA", "NT_DISPATCH", "NT_FARGS", "NT_CONDITION", "NT_WHEN", "NT_MATCH",
               "NT_TRY", "NT_RECEIVE", "NT_DECORATOR", "NT_MODULE", "NT_IMPORT", "NT_IMPORT_HIDING", "NT_INCLUDE",
               "NT_INCLUDE_HIDING", "NT_EXPORT", "NT_LOAD", "NT_TRAIT", "NT_EXTEND", "NT_GENERIC", "NT_METHOD",
               "NT_INTERFACE", "NT_DESCRIBE", "NT_BIND", "NT_THROW", "NT_REST", "NT_ASSIGN", "NT_ASSIGN_FORCE",
               "NT_CALL", "NT_JUXTAPOSITION", "NT_UNDEFINE", "NT_LOOKUP", "NT_IMPORTED_NAME", "NT_HEAD", "NT_TAIL",
               "NT_DROP", "NT_RANGE", "NT_MODIFY", "NT_OF", "NT_IS_IMPLEMENTED", "NT_AS", "NT_DELAY", "NT_LET",
               "NT_NOT", "NT_AND", "NT_OR", "NT_END_EXPR", "NT_END", ]


def node_type_to_s(ntype):
    return __NT_REPR__[ntype]
