# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_VOID = 3
NT_INT = 4
NT_FLOAT = 5
NT_STR = 6
NT_MULTI_STR = 7
NT_CHAR = 8
NT_WILDCARD = 9
NT_NAME = 10
NT_TEMPORARY = 11
NT_SYMBOL = 12
NT_TYPE = 13
NT_MAP = 14
NT_LIST = 15
NT_TUPLE = 16
NT_UNIT = 17
NT_CONS = 18
NT_COMMA = 19
NT_CASE = 20
NT_LENSE = 21
NT_LITERAL = 22
NT_FUN = 23
NT_DEF = 24
NT_DEF_PLUS = 25
NT_USE = 26
NT_LAMBDA = 27
NT_DISPATCH = 28
NT_FARGS = 29
NT_CONDITION = 30
NT_WHEN = 31
NT_MATCH = 32
NT_TRY = 33
NT_RECEIVE = 34
NT_MODULE = 35
NT_IMPORT = 36
NT_IMPORT_HIDING = 37
NT_IMPORT_FROM = 38
NT_IMPORT_FROM_HIDING = 39
NT_EXPORT = 40
NT_LOAD = 41
NT_TRAIT = 42
NT_EXTEND = 43
NT_GENERIC = 44
NT_METHOD = 45
NT_INTERFACE = 46
NT_DESCRIBE = 47
NT_BIND = 48
NT_THROW = 49
NT_REST = 50
NT_ASSIGN = 51
NT_CALL = 52
NT_JUXTAPOSITION = 53
NT_UNDEFINE = 54
NT_LOOKUP = 55
NT_IMPORTED_NAME = 56
NT_HEAD = 57
NT_TAIL = 58
NT_DROP = 59
NT_RANGE = 60
NT_MODIFY = 61
NT_OF = 62
NT_IS_IMPLEMENTED = 63
NT_AS = 64
NT_DELAY = 65
NT_LET = 66
NT_NOT = 67
NT_AND = 68
NT_OR = 69
NT_END_EXPR = 70
NT_END = 71
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_VOID", "NT_INT", "NT_FLOAT", "NT_STR", "NT_MULTI_STR", "NT_CHAR",
               "NT_WILDCARD", "NT_NAME", "NT_TEMPORARY", "NT_SYMBOL", "NT_TYPE", "NT_MAP", "NT_LIST", "NT_TUPLE",
               "NT_UNIT", "NT_CONS", "NT_COMMA", "NT_CASE", "NT_LENSE", "NT_LITERAL", "NT_FUN", "NT_DEF", "NT_DEF_PLUS",
               "NT_USE", "NT_LAMBDA", "NT_DISPATCH", "NT_FARGS", "NT_CONDITION", "NT_WHEN", "NT_MATCH", "NT_TRY",
               "NT_RECEIVE", "NT_MODULE", "NT_IMPORT", "NT_IMPORT_HIDING", "NT_IMPORT_FROM", "NT_IMPORT_FROM_HIDING",
               "NT_EXPORT", "NT_LOAD", "NT_TRAIT", "NT_EXTEND", "NT_GENERIC", "NT_METHOD", "NT_INTERFACE",
               "NT_DESCRIBE", "NT_BIND", "NT_THROW", "NT_REST", "NT_ASSIGN", "NT_CALL", "NT_JUXTAPOSITION",
               "NT_UNDEFINE", "NT_LOOKUP", "NT_IMPORTED_NAME", "NT_HEAD", "NT_TAIL", "NT_DROP", "NT_RANGE", "NT_MODIFY",
               "NT_OF", "NT_IS_IMPLEMENTED", "NT_AS", "NT_DELAY", "NT_LET", "NT_NOT", "NT_AND", "NT_OR", "NT_END_EXPR",
               "NT_END", ]


def node_type_to_s(ntype):
    return __NT_REPR__[ntype]
