TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_OPERATOR = 7
TT_VOID = 8
TT_NIL = 9
TT_SELF = 10
TT_FUN = 11
TT_CASE = 12
TT_BREAK = 13
TT_CONTINUE = 14
TT_WHILE = 15
TT_CLASS = 16
TT_EXTENDS = 17
TT_IF = 18
TT_ELIF = 19
TT_ELSE = 20
TT_THEN = 21
TT_WHEN = 22
TT_OF = 23
TT_LET = 24
TT_IN = 25
TT_IS = 26
TT_AS = 27
TT_NOT = 28
TT_AND = 29
TT_OR = 30
TT_TRUE = 31
TT_FALSE = 32
TT_TRY = 33
TT_THROW = 34
TT_CATCH = 35
TT_FINALLY = 36
TT_IMPORT = 37
TT_INCLUDE = 38
TT_FROM = 39
TT_HIDING = 40
TT_USE = 41
TT_FOR = 42
TT_END_EXPR = 43
TT_NEWLINE = 44
TT_INFIXL = 45
TT_INFIXR = 46
TT_PREFIX = 47
TT_ELLIPSIS = 48
TT_WILDCARD = 49
TT_GOTO = 50
TT_ARROW = 51
TT_AT_SIGN = 52
TT_DOUBLE_AT = 53
TT_DOLLAR = 54
TT_SHARP = 55
TT_JUXTAPOSITION = 56
TT_LCURLY = 57
TT_RCURLY = 58
TT_COMMA = 59
TT_ASSIGN = 60
TT_INFIX_DOT_LCURLY = 61
TT_LPAREN = 62
TT_RPAREN = 63
TT_LSQUARE = 64
TT_RSQUARE = 65
TT_DOT = 66
TT_COLON = 67
TT_DOUBLE_COLON = 68
TT_DOUBLE_DOT = 69
TT_BACKTICK_NAME = 70
TT_BACKTICK_OPERATOR = 71
TT_UNKNOWN = 72
# ************************ OBIN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_OPERATOR", u"TT_VOID", u"TT_NIL", u"TT_SELF", u"TT_FUN", u"TT_CASE", u"TT_BREAK", u"TT_CONTINUE",
               u"TT_WHILE", u"TT_CLASS", u"TT_EXTENDS", u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN",
               u"TT_OF", u"TT_LET", u"TT_IN", u"TT_IS", u"TT_AS", u"TT_NOT", u"TT_AND", u"TT_OR", u"TT_TRUE",
               u"TT_FALSE", u"TT_TRY", u"TT_THROW", u"TT_CATCH", u"TT_FINALLY", u"TT_IMPORT", u"TT_INCLUDE", u"TT_FROM",
               u"TT_HIDING", u"TT_USE", u"TT_FOR", u"TT_END_EXPR", u"TT_NEWLINE", u"TT_INFIXL", u"TT_INFIXR",
               u"TT_PREFIX", u"TT_ELLIPSIS", u"TT_WILDCARD", u"TT_GOTO", u"TT_ARROW", u"TT_AT_SIGN", u"TT_DOUBLE_AT",
               u"TT_DOLLAR", u"TT_SHARP", u"TT_JUXTAPOSITION", u"TT_LCURLY", u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN",
               u"TT_INFIX_DOT_LCURLY", u"TT_LPAREN", u"TT_RPAREN", u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON",
               u"TT_DOUBLE_COLON", u"TT_DOUBLE_DOT", u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_UNKNOWN", ]


def token_type_to_u(ttype):
    return __TT_REPR__[ttype]


def token_type_to_s(ttype):
    return str(__TT_REPR__[ttype])
