TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_OPERATOR = 7
TT_VOID = 8
TT_NIL = 9
TT_FUN = 10
TT_CASE = 11
TT_BREAK = 12
TT_CONTINUE = 13
TT_WHILE = 14
TT_CLASS = 15
TT_EXTENDS = 16
TT_IF = 17
TT_ELIF = 18
TT_ELSE = 19
TT_THEN = 20
TT_WHEN = 21
TT_OF = 22
TT_LET = 23
TT_IN = 24
TT_IS = 25
TT_AS = 26
TT_NOT = 27
TT_AND = 28
TT_OR = 29
TT_TRUE = 30
TT_FALSE = 31
TT_TRY = 32
TT_THROW = 33
TT_CATCH = 34
TT_FINALLY = 35
TT_IMPORT = 36
TT_INCLUDE = 37
TT_FROM = 38
TT_HIDING = 39
TT_USE = 40
TT_FOR = 41
TT_END_EXPR = 42
TT_NEWLINE = 43
TT_INFIXL = 44
TT_INFIXR = 45
TT_PREFIX = 46
TT_ELLIPSIS = 47
TT_WILDCARD = 48
TT_GOTO = 49
TT_ARROW = 50
TT_AT_SIGN = 51
TT_DOUBLE_AT = 52
TT_DOLLAR = 53
TT_SHARP = 54
TT_JUXTAPOSITION = 55
TT_LCURLY = 56
TT_RCURLY = 57
TT_COMMA = 58
TT_ASSIGN = 59
TT_INFIX_DOT_LCURLY = 60
TT_LPAREN = 61
TT_RPAREN = 62
TT_LSQUARE = 63
TT_RSQUARE = 64
TT_DOT = 65
TT_COLON = 66
TT_DOUBLE_COLON = 67
TT_DOUBLE_DOT = 68
TT_BACKTICK_NAME = 69
TT_BACKTICK_OPERATOR = 70
TT_UNKNOWN = 71
# ************************ OBIN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_OPERATOR", u"TT_VOID", u"TT_NIL", u"TT_FUN", u"TT_CASE", u"TT_BREAK", u"TT_CONTINUE", u"TT_WHILE",
               u"TT_CLASS", u"TT_EXTENDS", u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN", u"TT_OF",
               u"TT_LET", u"TT_IN", u"TT_IS", u"TT_AS", u"TT_NOT", u"TT_AND", u"TT_OR", u"TT_TRUE", u"TT_FALSE",
               u"TT_TRY", u"TT_THROW", u"TT_CATCH", u"TT_FINALLY", u"TT_IMPORT", u"TT_INCLUDE", u"TT_FROM",
               u"TT_HIDING", u"TT_USE", u"TT_FOR", u"TT_END_EXPR", u"TT_NEWLINE", u"TT_INFIXL", u"TT_INFIXR",
               u"TT_PREFIX", u"TT_ELLIPSIS", u"TT_WILDCARD", u"TT_GOTO", u"TT_ARROW", u"TT_AT_SIGN", u"TT_DOUBLE_AT",
               u"TT_DOLLAR", u"TT_SHARP", u"TT_JUXTAPOSITION", u"TT_LCURLY", u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN",
               u"TT_INFIX_DOT_LCURLY", u"TT_LPAREN", u"TT_RPAREN", u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON",
               u"TT_DOUBLE_COLON", u"TT_DOUBLE_DOT", u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_UNKNOWN", ]


def token_type_to_u(ttype):
    return __TT_REPR__[ttype]


def token_type_to_s(ttype):
    return str(__TT_REPR__[ttype])
