# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_VOID = 3
NT_INT = 4
NT_FLOAT = 5
NT_STR = 6
NT_CHAR = 7
NT_WILDCARD = 8
NT_NAME = 9
NT_TEMPORARY = 10
NT_SYMBOL = 11
NT_DERIVE = 12
NT_TYPE = 13
NT_UNION = 14
NT_MAP = 15
NT_LIST = 16
NT_TUPLE = 17
NT_UNIT = 18
NT_CONS = 19
NT_COMMA = 20
NT_CASE = 21
NT_FUN = 22
NT_FENV = 23
NT_CONDITION = 24
NT_TERNARY_CONDITION = 25
NT_WHEN = 26
NT_MATCH = 27
NT_TRY = 28
NT_MODULE = 29
NT_IMPORT = 30
NT_IMPORT_HIDING = 31
NT_IMPORT_FROM = 32
NT_IMPORT_FROM_HIDING = 33
NT_EXPORT = 34
NT_LOAD = 35
NT_TRAIT = 36
NT_IMPLEMENT = 37
NT_BIND = 38
NT_THROW = 39
NT_REST = 40
NT_ASSIGN = 41
NT_CALL = 42
NT_JUXTAPOSITION = 43
NT_UNDEFINE = 44
NT_LOOKUP = 45
NT_IMPORTED_NAME = 46
NT_HEAD = 47
NT_TAIL = 48
NT_DROP = 49
NT_RANGE = 50
NT_MODIFY = 51
NT_OF = 52
NT_AS = 53
NT_VAR = 54
NT_LAZY = 55
NT_AND = 56
NT_OR = 57
NT_END_EXPR = 58
NT_END = 59
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_VOID", "NT_INT", "NT_FLOAT", "NT_STR", "NT_CHAR", "NT_WILDCARD",
               "NT_NAME", "NT_TEMPORARY", "NT_SYMBOL", "NT_DERIVE", "NT_TYPE", "NT_UNION", "NT_MAP", "NT_LIST",
               "NT_TUPLE", "NT_UNIT", "NT_CONS", "NT_COMMA", "NT_CASE", "NT_FUN", "NT_FENV", "NT_CONDITION",
               "NT_TERNARY_CONDITION", "NT_WHEN", "NT_MATCH", "NT_TRY", "NT_MODULE", "NT_IMPORT", "NT_IMPORT_HIDING",
               "NT_IMPORT_FROM", "NT_IMPORT_FROM_HIDING", "NT_EXPORT", "NT_LOAD", "NT_TRAIT", "NT_IMPLEMENT", "NT_BIND",
               "NT_THROW", "NT_REST", "NT_ASSIGN", "NT_CALL", "NT_JUXTAPOSITION", "NT_UNDEFINE", "NT_LOOKUP",
               "NT_IMPORTED_NAME", "NT_HEAD", "NT_TAIL", "NT_DROP", "NT_RANGE", "NT_MODIFY", "NT_OF", "NT_AS", "NT_VAR",
               "NT_LAZY", "NT_AND", "NT_OR", "NT_END_EXPR", "NT_END", ]


def node_type_to_s(ntype):
    return __NT_REPR__[ntype]
