# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_VOID = 3
NT_INT = 4
NT_FLOAT = 5
NT_STR = 6
NT_MULTI_STR = 7
NT_CHAR = 8
NT_WILDCARD = 9
NT_NAME = 10
NT_TEMPORARY = 11
NT_SYMBOL = 12
NT_INTERFACE = 13
NT_GENERIC = 14
NT_TYPE = 15
NT_UNION = 16
NT_MAP = 17
NT_LIST = 18
NT_TUPLE = 19
NT_UNIT = 20
NT_CONS = 21
NT_COMMA = 22
NT_CASE = 23
NT_FUN = 24
NT_FENV = 25
NT_CONDITION = 26
NT_WHEN = 27
NT_MATCH = 28
NT_TRY = 29
NT_MODULE = 30
NT_IMPORT = 31
NT_IMPORT_HIDING = 32
NT_IMPORT_FROM = 33
NT_IMPORT_FROM_HIDING = 34
NT_EXPORT = 35
NT_LOAD = 36
NT_TRAIT = 37
NT_IMPLEMENT = 38
NT_EXTEND = 39
NT_BIND = 40
NT_THROW = 41
NT_REST = 42
NT_ASSIGN = 43
NT_CALL = 44
NT_JUXTAPOSITION = 45
NT_UNDEFINE = 46
NT_LOOKUP = 47
NT_IMPORTED_NAME = 48
NT_HEAD = 49
NT_TAIL = 50
NT_DROP = 51
NT_RANGE = 52
NT_MODIFY = 53
NT_OF = 54
NT_AS = 55
NT_DELAY = 56
NT_LET = 57
NT_AND = 58
NT_OR = 59
NT_END_EXPR = 60
NT_END = 61
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_VOID", "NT_INT", "NT_FLOAT", "NT_STR", "NT_MULTI_STR", "NT_CHAR",
               "NT_WILDCARD", "NT_NAME", "NT_TEMPORARY", "NT_SYMBOL", "NT_INTERFACE", "NT_GENERIC", "NT_TYPE",
               "NT_UNION", "NT_MAP", "NT_LIST", "NT_TUPLE", "NT_UNIT", "NT_CONS", "NT_COMMA", "NT_CASE", "NT_FUN",
               "NT_FENV", "NT_CONDITION", "NT_WHEN", "NT_MATCH", "NT_TRY", "NT_MODULE", "NT_IMPORT", "NT_IMPORT_HIDING",
               "NT_IMPORT_FROM", "NT_IMPORT_FROM_HIDING", "NT_EXPORT", "NT_LOAD", "NT_TRAIT", "NT_IMPLEMENT",
               "NT_EXTEND", "NT_BIND", "NT_THROW", "NT_REST", "NT_ASSIGN", "NT_CALL", "NT_JUXTAPOSITION", "NT_UNDEFINE",
               "NT_LOOKUP", "NT_IMPORTED_NAME", "NT_HEAD", "NT_TAIL", "NT_DROP", "NT_RANGE", "NT_MODIFY", "NT_OF",
               "NT_AS", "NT_DELAY", "NT_LET", "NT_AND", "NT_OR", "NT_END_EXPR", "NT_END", ]


def node_type_to_s(ntype):
    return __NT_REPR__[ntype]
