# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_INT = 3
NT_FLOAT = 4
NT_STR = 5
NT_CHAR = 6
NT_WILDCARD = 7
NT_NAME = 8
NT_TEMPORARY = 9
NT_SYMBOL = 10
NT_DERIVE = 11
NT_TYPE = 12
NT_MAP = 13
NT_LIST = 14
NT_TUPLE = 15
NT_UNIT = 16
NT_CONS = 17
NT_COMMA = 18
NT_FUN = 19
NT_FENV = 20
NT_CONDITION = 21
NT_TERNARY_CONDITION = 22
NT_WHEN = 23
NT_MATCH = 24
NT_TRY = 25
NT_MODULE = 26
NT_IMPORT = 27
NT_IMPORT_HIDING = 28
NT_IMPORT_FROM = 29
NT_IMPORT_FROM_HIDING = 30
NT_EXPORT = 31
NT_LOAD = 32
NT_TRAIT = 33
NT_IMPLEMENT = 34
NT_BIND = 35
NT_THROW = 36
NT_REST = 37
NT_ASSIGN = 38
NT_CALL = 39
NT_JUXTAPOSITION = 40
NT_UNDEFINE = 41
NT_LOOKUP = 42
NT_LOOKUP_SYMBOL = 43
NT_LOOKUP_MODULE = 44
NT_HEAD = 45
NT_TAIL = 46
NT_DROP = 47
NT_RANGE = 48
NT_MODIFY = 49
NT_OF = 50
NT_AS = 51
NT_VAR = 52
NT_LAZY = 53
NT_AND = 54
NT_OR = 55
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_INT", "NT_FLOAT", "NT_STR", "NT_CHAR", "NT_WILDCARD", "NT_NAME",
               "NT_TEMPORARY", "NT_SYMBOL", "NT_DERIVE", "NT_TYPE", "NT_MAP", "NT_LIST", "NT_TUPLE", "NT_UNIT",
               "NT_CONS", "NT_COMMA", "NT_FUN", "NT_FENV", "NT_CONDITION", "NT_TERNARY_CONDITION", "NT_WHEN",
               "NT_MATCH", "NT_TRY", "NT_MODULE", "NT_IMPORT", "NT_IMPORT_HIDING", "NT_IMPORT_FROM",
               "NT_IMPORT_FROM_HIDING", "NT_EXPORT", "NT_LOAD", "NT_TRAIT", "NT_IMPLEMENT", "NT_BIND", "NT_THROW",
               "NT_REST", "NT_ASSIGN", "NT_CALL", "NT_JUXTAPOSITION", "NT_UNDEFINE", "NT_LOOKUP", "NT_LOOKUP_SYMBOL",
               "NT_LOOKUP_MODULE", "NT_HEAD", "NT_TAIL", "NT_DROP", "NT_RANGE", "NT_MODIFY", "NT_OF", "NT_AS", "NT_VAR",
               "NT_LAZY", "NT_AND", "NT_OR", ]


def node_type_to_str(ttype):
    return __NT_REPR__[ttype]
