# ************************ OBIN NODES*****************************
NT_GOTO = 0
NT_TRUE = 1
NT_FALSE = 2
NT_NIL = 3
NT_VOID = 4
NT_INT = 5
NT_FLOAT = 6
NT_STR = 7
NT_MULTI_STR = 8
NT_CHAR = 9
NT_WILDCARD = 10
NT_NAME = 11
NT_TEMPORARY = 12
NT_SYMBOL = 13
NT_CLASS = 14
NT_MAP = 15
NT_ARRAY = 16
NT_UNIT = 17
NT_COMMA = 18
NT_CASE = 19
NT_LITERAL = 20
NT_BIND = 21
NT_FUN = 22
NT_FUN_ASSIGN = 23
NT_USE = 24
NT_LAMBDA = 25
NT_FARGS = 26
NT_CONDITION = 27
NT_WHEN = 28
NT_MATCH = 29
NT_TRY = 30
NT_DECORATOR = 31
NT_IMPORT = 32
NT_IMPORT_HIDING = 33
NT_INCLUDE = 34
NT_INCLUDE_HIDING = 35
NT_EXPORT = 36
NT_LOAD = 37
NT_EXTEND = 38
NT_MODIFY = 39
NT_THROW = 40
NT_REST = 41
NT_ASSIGN = 42
NT_ASSIGN_FORCE = 43
NT_CALL = 44
NT_JUXTAPOSITION = 45
NT_UNDEFINE = 46
NT_LOOKUP = 47
NT_HEAD = 48
NT_TAIL = 49
NT_DROP = 50
NT_RANGE = 51
NT_OF = 52
NT_AS = 53
NT_LET = 54
NT_NOT = 55
NT_AND = 56
NT_OR = 57
NT_END_EXPR = 58
NT_END = 59
# ************************ OBIN NODES REPR *****************************
__NT_REPR__ = ["NT_GOTO", "NT_TRUE", "NT_FALSE", "NT_NIL", "NT_VOID", "NT_INT", "NT_FLOAT", "NT_STR", "NT_MULTI_STR",
               "NT_CHAR", "NT_WILDCARD", "NT_NAME", "NT_TEMPORARY", "NT_SYMBOL", "NT_CLASS", "NT_MAP", "NT_ARRAY",
               "NT_UNIT", "NT_COMMA", "NT_CASE", "NT_LITERAL", "NT_BIND", "NT_FUN", "NT_FUN_ASSIGN", "NT_USE",
               "NT_LAMBDA", "NT_FARGS", "NT_CONDITION", "NT_WHEN", "NT_MATCH", "NT_TRY", "NT_DECORATOR", "NT_IMPORT",
               "NT_IMPORT_HIDING", "NT_INCLUDE", "NT_INCLUDE_HIDING", "NT_EXPORT", "NT_LOAD", "NT_EXTEND", "NT_MODIFY",
               "NT_THROW", "NT_REST", "NT_ASSIGN", "NT_ASSIGN_FORCE", "NT_CALL", "NT_JUXTAPOSITION", "NT_UNDEFINE",
               "NT_LOOKUP", "NT_HEAD", "NT_TAIL", "NT_DROP", "NT_RANGE", "NT_OF", "NT_AS", "NT_LET", "NT_NOT", "NT_AND",
               "NT_OR", "NT_END_EXPR", "NT_END", ]


def node_type_to_s(ntype):
    return __NT_REPR__[ntype]
