# ************************ OBIN TOKENS*****************************
TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_OPERATOR = 7
TT_VOID = 8
TT_NIL = 9
TT_TRUE = 10
TT_FALSE = 11
TT_SELF = 12
TT_FUN = 13
TT_RECEIVE = 14
TT_MATCH = 15
TT_CASE = 16
TT_WHILE = 17
TT_FOR = 18
TT_BREAK = 19
TT_CONTINUE = 20
TT_CLASS = 21
TT_EXTENDS = 22
TT_IF = 23
TT_ELIF = 24
TT_ELSE = 25
TT_THEN = 26
TT_WHEN = 27
TT_TRY = 28
TT_THROW = 29
TT_CATCH = 30
TT_FINALLY = 31
TT_LET = 32
TT_OF = 33
TT_IN = 34
TT_IS = 35
TT_AS = 36
TT_NOT = 37
TT_AND = 38
TT_OR = 39
TT_IMPORT = 40
TT_INCLUDE = 41
TT_FROM = 42
TT_HIDING = 43
TT_USE = 44
TT_END_EXPR = 45
TT_NEWLINE = 46
TT_INFIXL = 47
TT_INFIXR = 48
TT_PREFIX = 49
TT_TRIPLE_DOT = 50
TT_WILDCARD = 51
TT_GOTO = 52
TT_ARROW = 53
TT_AT_SIGN = 54
TT_DOUBLE_AT = 55
TT_DOLLAR = 56
TT_SHARP = 57
TT_JUXTAPOSITION = 58
TT_LCURLY = 59
TT_RCURLY = 60
TT_COMMA = 61
TT_ASSIGN = 62
TT_INFIX_DOT_LCURLY = 63
TT_LPAREN = 64
TT_RPAREN = 65
TT_LSQUARE = 66
TT_RSQUARE = 67
TT_DOT = 68
TT_COLON = 69
TT_DOUBLE_COLON = 70
TT_DOUBLE_DOT = 71
TT_BACKTICK_NAME = 72
TT_BACKTICK_OPERATOR = 73
TT_LT = 74
TT_GT = 75
TT_GE = 76
TT_LE = 77
TT_EQ = 78
TT_NE = 79
TT_BOR = 80
TT_BNOT = 81
TT_BAND = 82
TT_BXOR = 83
TT_BRSH = 84
TT_BLSH = 85
TT_ADD = 86
TT_SUB = 87
TT_MUL = 88
TT_DIV = 89
TT_POW = 90
TT_NEG = 91
TT_UNKNOWN = 92
# ************************ OBIN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_OPERATOR", u"TT_VOID", u"TT_NIL", u"TT_TRUE", u"TT_FALSE", u"TT_SELF", u"TT_FUN", u"TT_RECEIVE",
               u"TT_MATCH", u"TT_CASE", u"TT_WHILE", u"TT_FOR", u"TT_BREAK", u"TT_CONTINUE", u"TT_CLASS", u"TT_EXTENDS",
               u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN", u"TT_TRY", u"TT_THROW", u"TT_CATCH",
               u"TT_FINALLY", u"TT_LET", u"TT_OF", u"TT_IN", u"TT_IS", u"TT_AS", u"TT_NOT", u"TT_AND", u"TT_OR",
               u"TT_IMPORT", u"TT_INCLUDE", u"TT_FROM", u"TT_HIDING", u"TT_USE", u"TT_END_EXPR", u"TT_NEWLINE",
               u"TT_INFIXL", u"TT_INFIXR", u"TT_PREFIX", u"TT_ELLIPSIS", u"TT_WILDCARD", u"TT_GOTO", u"TT_ARROW",
               u"TT_AT_SIGN", u"TT_DOUBLE_AT", u"TT_DOLLAR", u"TT_SHARP", u"TT_JUXTAPOSITION", u"TT_LCURLY",
               u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN", u"TT_INFIX_DOT_LCURLY", u"TT_LPAREN", u"TT_RPAREN",
               u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON", u"TT_DOUBLE_COLON", u"TT_DOUBLE_DOT",
               u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_LT", u"TT_GT", u"TT_GE", u"TT_LE", u"TT_EQ", u"TT_NE",
               u"TT_BOR", u"TT_BNOT", u"TT_BAND", u"TT_BXOR", u"TT_BRSH", u"TT_BLSH", u"TT_ADD", u"TT_SUB", u"TT_MUL",
               u"TT_DIV", u"TT_POW", u"TT_NEG", u"TT_UNKNOWN", ]


def token_type_to_u(ttype):
    return __TT_REPR__[ttype]


def token_type_to_s(ttype):
    return str(__TT_REPR__[ttype])
