# ************************ OBIN TOKENS*****************************
TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_TICKNAME = 7
TT_OPERATOR = 8
TT_FUN = 9
TT_MATCH = 10
TT_WITH = 11
TT_CASE = 12
TT_EXTEND = 13
TT_TYPE = 14
TT_IF = 15
TT_ELIF = 16
TT_ELSE = 17
TT_THEN = 18
TT_WHEN = 19
TT_OF = 20
TT_LET = 21
TT_IN = 22
TT_AS = 23
TT_AND = 24
TT_OR = 25
TT_TRUE = 26
TT_FALSE = 27
TT_TRY = 28
TT_THROW = 29
TT_CATCH = 30
TT_FINALLY = 31
TT_MODULE = 32
TT_IMPORT = 33
TT_FROM = 34
TT_HIDING = 35
TT_HIDE = 36
TT_EXPORT = 37
TT_TRAIT = 38
TT_USE = 39
TT_GENERIC = 40
TT_INTERFACE = 41
TT_END_EXPR = 42
TT_NEWLINE = 43
TT_ELLIPSIS = 44
TT_WILDCARD = 45
TT_GOTO = 46
TT_ARROW = 47
TT_FAT_ARROW = 48
TT_AT_SIGN = 49
TT_SHARP = 50
TT_JUXTAPOSITION = 51
TT_LCURLY = 52
TT_RCURLY = 53
TT_COMMA = 54
TT_ASSIGN = 55
TT_INFIX_DOT_LCURLY = 56
TT_INFIX_DOT_LPAREN = 57
TT_INFIX_DOT_LSQUARE = 58
TT_LPAREN = 59
TT_RPAREN = 60
TT_PREFIX = 61
TT_INFIXL = 62
TT_INFIXR = 63
TT_LSQUARE = 64
TT_RSQUARE = 65
TT_DOT = 66
TT_COLON = 67
TT_DOUBLE_COLON = 68
TT_DOUBLE_DOT = 69
TT_BACKTICK_NAME = 70
TT_BACKTICK_OPERATOR = 71
TT_UNKNOWN = 72
# ************************ OBIN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_TICKNAME", u"TT_OPERATOR", u"TT_FUN", u"TT_MATCH", u"TT_WITH", u"TT_CASE", u"TT_EXTEND", u"TT_TYPE",
               u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN", u"TT_OF", u"TT_LET", u"TT_IN", u"TT_AS",
               u"TT_AND", u"TT_OR", u"TT_TRUE", u"TT_FALSE", u"TT_TRY", u"TT_THROW", u"TT_CATCH", u"TT_FINALLY",
               u"TT_MODULE", u"TT_IMPORT", u"TT_FROM", u"TT_HIDING", u"TT_HIDE", u"TT_EXPORT", u"TT_TRAIT", u"TT_USE",
               u"TT_GENERIC", u"TT_INTERFACE", u"TT_END_EXPR", u"TT_NEWLINE", u"TT_ELLIPSIS", u"TT_WILDCARD",
               u"TT_GOTO", u"TT_ARROW", u"TT_FAT_ARROW", u"TT_AT_SIGN", u"TT_SHARP", u"TT_JUXTAPOSITION", u"TT_LCURLY",
               u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN", u"TT_INFIX_DOT_LCURLY", u"TT_INFIX_DOT_LPAREN",
               u"TT_INFIX_DOT_LSQUARE", u"TT_LPAREN", u"TT_RPAREN", u"TT_PREFIX", u"TT_INFIXL", u"TT_INFIXR",
               u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON", u"TT_DOUBLE_COLON", u"TT_DOUBLE_DOT",
               u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_UNKNOWN", ]


def token_type_to_s(ttype):
    return __TT_REPR__[ttype]
