
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[239] =
    {   0,
        0,    0,   74,   73,   72,    2,   73,   73,   71,   64,
       56,   73,   51,   52,   62,   61,   49,   60,   55,   63,
        5,    4,   46,   45,   65,   50,   66,   67,   70,   70,
       53,   73,   54,   59,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   47,   58,   48,   57,    1,
       72,   44,    0,   69,    0,   71,   33,   34,    0,    0,
        0,   31,   29,   30,   39,    0,    8,   32,    9,    5,
        0,    0,    0,    4,   38,   42,   41,   40,   43,   37,
       70,    0,    0,    0,    0,   35,   70,   70,   70,   70,
       70,   16,   70,   70,   70,   70,   20,   70,   26,   70,

       70,   36,    1,    0,    0,    0,    0,    0,    6,   68,
        0,    0,    0,    0,    0,    0,   28,    0,    8,    0,
        9,    0,    7,    0,    3,    0,    0,    0,    0,    0,
        0,   25,   70,   70,   70,   70,   70,   22,   18,   70,
       27,   70,   70,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    8,    0,    9,    7,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    0,   70,   14,
       24,   70,   17,   23,   21,   70,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    0,    0,    0,   13,   70,   19,    0,

        0,    0,    0,    0,    0,   11,    0,   12,   10,    0,
        0,    0,    0,    0,   70,   70,    0,    0,    0,    0,
       11,   12,    0,    0,   70,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   33,
       31,   31,   31,   31,   34,   31,   31,   35,   31,   31,
       36,   37,   38,   39,   31,    1,   40,   41,   42,   43,

       44,   45,   31,   46,   47,   31,   48,   49,   31,   50,
       51,   33,   31,   52,   53,   54,   55,   56,   57,   58,
       31,   31,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        8,    8,    8,    9,    9,    1,   10,    1,    1,    6,
        6,    7,    7,    7,    6,    8,    8,    8,    8,   10,
        8,   10,    8,   10,    9,   10,    8,   10,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[299] =
    {   0,
        0,   60,  451,  694,  694,  694,  425,   59,    0,  424,
      422,   63,  694,  694,  417,  416,  694,   42,   52,  403,
       57,   62,  694,  694,   60,   62,   64,  694,  390,   60,
      694,   59,  694,  400,   57,   43,   65,   61,   71,   62,
       66,   67,   73,   82,   85,  694,  395,  694,  694,  694,
      120,  694,  120,  694,  110,    0,  694,  694,  124,  122,
      116,  694,  694,  694,  694,  392,  134,  694,  156,  170,
      175,  127,  391,  189,  694,  694,  694,  694,  694,  694,
      369,  103,  368,    0,    0,  694,   96,  105,  103,  123,
      130,  366,  144,  170,  132,  161,  360,  166,  359,  178,

      115,  694,  694,  213,  206,    0,    0,    0,  694,  694,
      204,  226,    0,    0,    0,    0,  694,  221,  694,  233,
      694,  211,  236,    0,  211,    0,    0,  211,  231,    0,
        0,  337,  133,  190,  221,  223,  227,  329,  326,  230,
      322,  224,  238,  259,    0,  291,    0,  263,  285,    0,
      327,    0,  370,  271,  294,  282,  330,  694,  311,  309,
      362,    0,    0,  694,  288,    0,    0,    0,  145,  293,
      292,  239,  290,  257,  247,  262,  303,    0,    0,    0,
      367,  351,    0,    0,    0,    0,  402,  410,  297,  413,
        0,    0,  382,  453,    0,    0,  232,  243,  165,    0,

        0,  328,    0,    0,  374,  416,  419,  456,  694,    0,
        0,  348,    0,    0,  101,  286,    0,  347,    0,  407,
      694,  694,    0,    0,  308,    0,    0,    0,    0,   38,
        0,    0,    0,    0,    0,    0,    0,  694,  505,  515,
      525,  530,  538,  548,  556,  562,  569,  574,  576,  578,
      580,  582,  587,  592,  594,  596,  598,  600,  602,  604,
      609,  614,  616,  618,  620,  622,  624,  626,  628,  630,
      632,  634,  636,  638,  640,  642,  644,  646,  648,  650,
      652,  654,  656,  658,  660,  662,  664,  666,  668,  670,
      672,  674,  676,  678,  680,  682,  684,  686

    } ;

static yyconst flex_int16_t yy_def[299] =
    {   0,
      238,    1,  238,  238,  238,  238,  238,  239,  240,  238,
      238,  241,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  242,  242,
      238,  238,  238,  238,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  238,  238,  238,  238,  238,
      238,  238,  239,  238,  243,  240,  238,  238,  241,  244,
      245,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  246,  238,  238,  238,  238,  238,  238,  238,
      242,  238,  247,  248,  249,  238,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  238,  238,  238,  239,  250,  251,  252,  238,  238,
      253,  241,  254,  255,  256,  257,  238,  238,  238,  238,
      238,  238,  238,  258,  246,  259,  260,  247,  261,  262,
      263,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  239,  264,  239,  265,  244,  241,  266,
      244,  267,  241,  238,  238,  238,  238,  238,  258,  258,
      238,  268,  269,  238,  247,  270,  271,  272,  242,  242,
      242,  242,  242,  242,  242,  242,  239,  273,  146,  274,
      244,  241,  275,  151,  276,  153,  238,  238,  238,  238,
      277,  278,  247,  247,  279,  280,  242,  242,  242,  281,

      282,  244,  283,  284,  238,  238,  238,  238,  238,  285,
      286,  247,  194,  287,  242,  242,  288,  239,  289,  244,
      238,  238,  290,  291,  242,  292,  293,  294,  295,  242,
      296,  297,  298,  280,  282,  284,  286,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238

    } ;

static yyconst flex_int16_t yy_nxt[757] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   30,   29,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   29,   41,   29,   29,   42,
       43,   29,   29,   44,   30,   29,   45,   29,   46,   47,
       48,   49,   50,   51,   54,   60,   64,   65,   66,   83,
       67,   67,   67,   69,   82,   70,   70,   71,   69,   82,
       74,   74,   74,   75,   76,   72,   77,   78,   79,   80,
       72,   73,   84,   82,   88,   55,   82,   82,   82,   61,

       72,   82,   82,   82,   89,   72,   87,   82,   90,   82,
       97,   92,   95,   85,   73,   91,   96,   98,   82,   93,
       94,   82,  103,  104,   99,   54,   60,  100,  105,  105,
      101,  110,   82,  109,  112,  112,  126,   82,  132,   82,
      122,   82,  122,  106,  107,  123,  123,  123,  133,  113,
      114,   82,   67,   67,   67,  134,   55,  127,  111,   82,
       61,  143,  118,  119,  108,  119,   82,  107,   82,   82,
      115,  135,  169,  116,   67,   67,   67,  118,  119,  136,
       82,   82,  119,  139,  120,  121,   69,  121,   70,   70,
       71,   69,  197,   71,   71,   71,  137,   82,   72,  120,

      121,   82,   82,   72,  121,   69,   82,   74,   74,   74,
      140,   54,  138,   72,   82,  103,  104,   72,   72,  141,
      164,  142,  148,  148,  144,  144,   82,  160,   60,  123,
      123,  123,   72,  170,  154,  109,  154,  113,  114,  155,
      155,  155,   55,  161,  149,  149,  156,  129,  156,  165,
      165,  157,  157,  157,  123,  123,  123,   82,  115,   82,
       82,  114,   61,   82,   54,  158,   82,  158,   82,  171,
      173,  174,  110,  175,   82,   82,  172,  177,  177,   82,
      158,  181,  181,   82,  158,  198,  176,   60,  166,  155,
      155,  155,  216,   82,  109,   55,   54,  164,   82,  111,

      157,  157,  157,  182,  182,  199,  193,  193,   54,  179,
      179,  179,  155,  155,  155,  190,  190,  190,  179,  179,
      179,   61,   82,  119,  129,  119,   82,   55,   82,   82,
      179,  179,  179,  179,  179,  179,  110,  110,  119,   55,
      225,  188,  119,  187,   82,  184,  184,  184,  157,  157,
      157,  230,   54,   60,  184,  184,  184,  164,   82,  121,
      109,  121,   82,  111,  111,   82,  184,  184,  184,  184,
      184,  184,   60,   82,  121,  189,  110,  189,  121,  109,
      190,  190,  190,   55,  129,  202,  202,   61,  186,  186,
      186,  164,  206,  206,  206,   82,   82,  186,  186,  186,

      212,  212,   82,  111,  129,   82,   61,  124,  117,  186,
      186,  186,  186,  186,  186,  205,  110,  205,  129,  102,
      206,  206,  206,  207,   86,  207,   82,   68,  208,  208,
      208,  190,  190,  190,  206,  206,  206,  208,  208,  208,
       63,   62,  209,  111,  209,  221,   58,  221,   57,   52,
      238,  238,  238,  238,  238,  238,  238,  209,  238,  238,
      221,  209,  164,  238,  221,  238,  238,  238,  238,  238,
      238,  213,  213,  213,  208,  208,  208,  238,  238,  238,
      213,  213,  213,  238,  238,  222,  238,  222,  238,  129,
      238,  238,  213,  213,  213,  213,  213,  213,  238,  238,

      222,  238,  238,  238,  222,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   56,  238,   56,   56,   56,
       56,   56,   56,   56,   56,   59,   59,   59,  238,   59,
       59,   59,   59,   59,   59,   81,   81,   81,   81,   81,
       53,   53,  238,   53,  238,  238,   53,   53,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   59,   59,
      238,   59,  238,  238,   59,   59,  125,  125,  125,  128,
      238,  128,  238,  128,  128,  128,  128,  128,  128,  130,
      130,  131,  131,  145,  145,  146,  146,  147,  147,   60,
       60,  238,   60,  238,  238,   60,   60,  150,  150,  151,

      151,  152,  152,  153,  153,  159,  159,  162,  162,  163,
      163,  128,  128,  238,  128,  238,  238,  238,  128,  167,
      167,  168,  168,  178,  178,  180,  180,  183,  183,  185,
      185,  191,  191,  192,  192,  194,  194,  195,  195,  196,
      196,  200,  200,  201,  201,  203,  203,  204,  204,  210,
      210,  211,  211,  214,  214,  215,  215,  217,  217,  218,
      218,  219,  219,  220,  220,  223,  223,   81,   81,  224,
      224,  226,  226,  227,  227,  228,  228,  229,  229,  231,
      231,  232,  232,  233,  233,  234,  234,  235,  235,  236,
      236,  237,  237,    3,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yyconst flex_int16_t yy_chk[757] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    8,   12,   18,   18,   19,   30,
       19,   19,   19,   21,  230,   21,   21,   21,   22,   36,
       22,   22,   22,   25,   25,   21,   26,   26,   27,   27,
       22,   21,   32,   35,   36,    8,   30,   38,   40,   12,

       21,   37,   41,   42,   37,   22,   35,   39,   37,   43,
       41,   38,   40,   32,   21,   37,   40,   42,   44,   39,
       39,   45,   51,   51,   43,   53,   59,   44,   55,   55,
       45,   60,   87,   59,   61,   61,   82,  215,   87,   89,
       72,   88,   72,   55,   55,   72,   72,   72,   88,   61,
       61,  101,   67,   67,   67,   89,   53,   82,   60,   90,
       59,  101,   67,   67,   55,   67,   91,   55,   95,  133,
       61,   90,  133,   61,   69,   69,   69,   67,   67,   91,
       93,  169,   67,   95,   69,   69,   70,   69,   70,   70,
       70,   71,  169,   71,   71,   71,   93,   96,   70,   69,

       69,  199,   98,   71,   69,   74,   94,   74,   74,   74,
       96,  105,   94,   70,  100,  104,  104,   74,   71,   98,
      128,  100,  111,  111,  105,  105,  134,  125,  112,  122,
      122,  122,   74,  134,  118,  112,  118,  111,  111,  118,
      118,  118,  105,  125,  112,  112,  120,  128,  120,  129,
      129,  120,  120,  120,  123,  123,  123,  135,  111,  136,
      142,  111,  112,  137,  144,  123,  140,  123,  197,  135,
      137,  140,  148,  142,  143,  172,  136,  144,  144,  198,
      123,  148,  148,  175,  123,  172,  143,  149,  129,  154,
      154,  154,  198,  174,  149,  144,  146,  165,  176,  148,

      156,  156,  156,  149,  149,  176,  165,  165,  177,  146,
      146,  146,  155,  155,  155,  189,  189,  189,  146,  146,
      146,  149,  216,  155,  165,  155,  173,  146,  171,  170,
      146,  146,  146,  146,  146,  146,  151,  202,  155,  177,
      216,  160,  155,  159,  225,  151,  151,  151,  157,  157,
      157,  225,  218,  182,  151,  151,  151,  212,  141,  157,
      182,  157,  139,  151,  202,  138,  151,  151,  151,  151,
      151,  151,  153,  132,  157,  161,  181,  161,  157,  153,
      161,  161,  161,  218,  212,  181,  181,  182,  153,  153,
      153,  193,  205,  205,  205,   99,   97,  153,  153,  153,

      193,  193,   92,  181,   83,   81,  153,   73,   66,  153,
      153,  153,  153,  153,  153,  187,  220,  187,  193,   47,
      187,  187,  187,  188,   34,  188,   29,   20,  188,  188,
      188,  190,  190,  190,  206,  206,  206,  207,  207,  207,
       16,   15,  190,  220,  190,  206,   11,  206,   10,    7,
        3,    0,    0,    0,    0,    0,    0,  190,    0,    0,
      206,  190,  194,    0,  206,    0,    0,    0,    0,    0,
        0,  194,  194,  194,  208,  208,  208,    0,    0,    0,
      194,  194,  194,    0,    0,  208,    0,  208,    0,  194,
        0,    0,  194,  194,  194,  194,  194,  194,    0,    0,

      208,    0,    0,    0,  208,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  240,    0,  240,  240,  240,
      240,  240,  240,  240,  240,  241,  241,  241,    0,  241,
      241,  241,  241,  241,  241,  242,  242,  242,  242,  242,
      243,  243,    0,  243,    0,    0,  243,  243,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  245,  245,
        0,  245,    0,    0,  245,  245,  246,  246,  246,  247,
        0,  247,    0,  247,  247,  247,  247,  247,  247,  248,
      248,  249,  249,  250,  250,  251,  251,  252,  252,  253,
      253,    0,  253,    0,    0,  253,  253,  254,  254,  255,

      255,  256,  256,  257,  257,  258,  258,  259,  259,  260,
      260,  261,  261,    0,  261,    0,    0,    0,  261,  262,
      262,  263,  263,  264,  264,  265,  265,  266,  266,  267,
      267,  268,  268,  269,  269,  270,  270,  271,  271,  272,
      272,  273,  273,  274,  274,  275,  275,  276,  276,  277,
      277,  278,  278,  279,  279,  280,  280,  281,  281,  282,
      282,  283,  283,  284,  284,  285,  285,  286,  286,  287,
      287,  288,  288,  289,  289,  290,  290,  291,  291,  292,
      292,  293,  293,  294,  294,  295,  295,  296,  296,  297,
      297,  298,  298,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <stdio.h>
#include <stdlib.h>

typedef enum {
    TT_ENDSTREAM = 0,
    TT_INT = 1,
    TT_FLOAT = 2,
    TT_STR = 3,
    TT_CHAR = 4,
    TT_NAME = 5,
    TT_NEWLINE = 6,
    TT_BREAK = 7,
    TT_CASE = 8,
    TT_CONTINUE = 9,
    TT_DO = 10,
    TT_ELSE = 11,
    TT_FOR = 12,
    TT_WHILE = 13,
    TT_IF = 14,
    TT_THEN = 15,
    TT_END = 16,
    TT_FUNC = 17,
    TT_CELL = 18,
    TT_AND = 19,
    TT_OR = 20,
    TT_NOT = 21,
    TT_ELLIPSIS = 22,
    TT_ADD_ASSIGN = 23,
    TT_SUB_ASSIGN = 24,
    TT_MUL_ASSIGN = 25,
    TT_DIV_ASSIGN = 26,
    TT_MOD_ASSIGN = 27,
    TT_AND_ASSIGN = 28,
    TT_XOR_ASSIGN = 29,
    TT_OR_ASSIGN = 30,
    TT_RSHIFT = 31,
    TT_LSHIFT = 32,
    TT_ARROW = 33,
    TT_FAT_ARROW = 34,
    TT_EQ = 35,
    TT_LE = 36,
    TT_GE = 37,
    TT_NE = 38,
    TT_SEMI = 39,
    TT_COLON = 40,
    TT_LCURLY = 41,
    TT_RCURLY = 42,
    TT_COMMA = 43,
    TT_ASSIGN = 44,
    TT_LPAREN = 45,
    TT_RPAREN = 46,
    TT_LSQUARE = 47,
    TT_RSQUARE = 48,
    TT_DOT = 49,
    TT_BITAND = 50,
    TT_BITNOT = 51,
    TT_BITOR = 52,
    TT_BITXOR = 53,
    TT_SUB = 54,
    TT_ADD = 55,
    TT_MUL = 56,
    TT_DIVIDE = 57,
    TT_MOD = 58,
    TT_LESS = 59,
    TT_GREATER = 60,
    TT_QUESTION = 61,
} TokenType;

/* some complex named patterns */
/* Universal Character Name */
#line 791 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 98 "lexer.l"

#line 1022 "lex.yy.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 694 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 99 "lexer.l"
{/* Ignore blank lines. */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 100 "lexer.l"
{ return TT_NEWLINE;  }
	YY_BREAK
/* constants */
case 3:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return TT_INT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return TT_INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return TT_INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return TT_INT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return TT_FLOAT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return TT_BREAK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return TT_CASE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return TT_CONTINUE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return TT_DO; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return TT_ELSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return TT_FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return TT_WHILE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return TT_IF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return TT_THEN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return TT_END; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return TT_FUNC; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return TT_CELL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return TT_AND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return TT_OR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return TT_NOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return TT_ELLIPSIS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return TT_ADD_ASSIGN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return TT_SUB_ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return TT_MUL_ASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return TT_DIV_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return TT_MOD_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return TT_AND_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return TT_XOR_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return TT_OR_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return TT_RSHIFT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return TT_LSHIFT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return TT_ARROW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return TT_FAT_ARROW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return TT_EQ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return TT_LE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return TT_GE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return TT_NE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return TT_SEMI; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return TT_COLON; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return TT_LCURLY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return TT_RCURLY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return TT_COMMA; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return TT_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return TT_LPAREN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return TT_RPAREN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return TT_LSQUARE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return TT_RSQUARE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return TT_DOT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return TT_BITAND; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return TT_BITNOT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return TT_BITOR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return TT_BITXOR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return TT_SUB; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return TT_ADD; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return TT_MUL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return TT_DIVIDE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return TT_MOD; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return TT_LESS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return TT_GREATER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return TT_QUESTION; }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 171 "lexer.l"
{return TT_CHAR;}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 172 "lexer.l"
{return TT_STR;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 174 "lexer.l"
{return TT_NAME;}
	YY_BREAK
/* Ignore comments and whitespace. */
case 71:
YY_RULE_SETUP
#line 178 "lexer.l"
{}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 179 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 181 "lexer.l"
{return TT_ENDSTREAM;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 183 "lexer.l"
ECHO;
	YY_BREAK
#line 1494 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 183 "lexer.l"


 
const char * TokenTypeStr(TokenType type) {
  switch(type) {
   case TT_ENDSTREAM: return "TT_ENDSTREAM";
    case TT_INT: return "TT_INT";
    case TT_FLOAT: return "TT_FLOAT";
    case TT_STR: return "TT_STR";
    case TT_CHAR: return "TT_CHAR";
    case TT_NAME: return "TT_NAME";
    case TT_NEWLINE: return "TT_NEWLINE";
    case TT_BREAK: return "TT_BREAK";
    case TT_CASE: return "TT_CASE";
    case TT_CONTINUE: return "TT_CONTINUE";
    case TT_DO: return "TT_DO";
    case TT_ELSE: return "TT_ELSE";
    case TT_FOR: return "TT_FOR";
    case TT_WHILE: return "TT_WHILE";
    case TT_IF: return "TT_IF";
    case TT_THEN: return "TT_THEN";
    case TT_END: return "TT_END";
    case TT_FUNC: return "TT_FUNC";
    case TT_CELL: return "TT_CELL";
    case TT_AND: return "TT_AND";
    case TT_OR: return "TT_OR";
    case TT_NOT: return "TT_NOT";
    case TT_ELLIPSIS: return "TT_ELLIPSIS";
    case TT_ADD_ASSIGN: return "TT_ADD_ASSIGN";
    case TT_SUB_ASSIGN: return "TT_SUB_ASSIGN";
    case TT_MUL_ASSIGN: return "TT_MUL_ASSIGN";
    case TT_DIV_ASSIGN: return "TT_DIV_ASSIGN";
    case TT_MOD_ASSIGN: return "TT_MOD_ASSIGN";
    case TT_AND_ASSIGN: return "TT_AND_ASSIGN";
    case TT_XOR_ASSIGN: return "TT_XOR_ASSIGN";
    case TT_OR_ASSIGN: return "TT_OR_ASSIGN";
    case TT_RSHIFT: return "TT_RSHIFT";
    case TT_LSHIFT: return "TT_LSHIFT";
    case TT_ARROW: return "TT_ARROW";
    case TT_FAT_ARROW: return "TT_FAT_ARROW";
    case TT_EQ: return "TT_EQ";
    case TT_LE: return "TT_LE";
    case TT_GE: return "TT_GE";
    case TT_NE: return "TT_NE";
    case TT_SEMI: return "TT_SEMI";
    case TT_COLON: return "TT_COLON";
    case TT_LCURLY: return "TT_LCURLY";
    case TT_RCURLY: return "TT_RCURLY";
    case TT_COMMA: return "TT_COMMA";
    case TT_ASSIGN: return "TT_ASSIGN";
    case TT_LPAREN: return "TT_LPAREN";
    case TT_RPAREN: return "TT_RPAREN";
    case TT_LSQUARE: return "TT_LSQUARE";
    case TT_RSQUARE: return "TT_RSQUARE";
    case TT_DOT: return "TT_DOT";
    case TT_BITAND: return "TT_BITAND";
    case TT_BITNOT: return "TT_BITNOT";
    case TT_BITOR: return "TT_BITOR";
    case TT_BITXOR: return "TT_BITXOR";
    case TT_SUB: return "TT_SUB";
    case TT_ADD: return "TT_ADD";
    case TT_MUL: return "TT_MUL";
    case TT_DIVIDE: return "TT_DIVIDE";
    case TT_MOD: return "TT_MOD";
    case TT_LESS: return "TT_LESS";
    case TT_GREATER: return "TT_GREATER";
    case TT_QUESTION: return "TT_QUESTION";
  }
}

typedef struct {
    const char * data;
    int length;
    TokenType type;
    int line;
} Token;

Token make_token(TokenType type, const char* data, int line) {
  Token token;
  token.type = type;
  token.data = strdup(data);
  token.line = line;
}


int main () {
 yyscan_t scanner;
 int tok_type;

 yylex_init(&scanner);

 while ((tok_type=yylex(scanner)) != TT_ENDSTREAM) {
    printf("%s <%s>,\n", TokenTypeStr(tok_type), yyget_text(scanner));
 }
    
 yylex_destroy(scanner);
 return 0;
}

