from jinja2 import Template
def render(body, data):
    tpl = Template(body)
    return tpl.render(data)

def mktype(name, traits, ctors=None):
    t = dict(name=name, traits=traits)
    if ctors is not None:
        for ctor in ctors:
            ctor["union"] = t

    t["ctors"] = ctors if ctors is not None else []
    return t

def mkctor(name):
    return dict(name=name)

A = "Any"
N = "Number"
C = "Callable"

TYPES = [
    mktype("Bool", [A], [mkctor("True"), mkctor("False")]),
    mktype("Option", [A], [mkctor("Nil")]),
    mktype("Char", [A]),

    mktype("Int", [N, A]),
    mktype("Float", [N, A]),

    mktype("Symbol", [A]),
    mktype("String", [A]),
    mktype("List", [A]),
    mktype("Vector", [A]),
    mktype("Tuple", [A]),
    mktype("Map", [A]),

    mktype("Function", [C, A]),
    mktype("Generic", [C, A]),
    mktype("Method", [C, A]),
    mktype("NativeFunction", [C, A]),
    mktype("Fiber", [C, A]),

    mktype("Trait", [A]),
    mktype("Datatype", [A]),
    mktype("TVar", [A]),
    mktype("Env", [A]),
]

def gen_declaration():
    import sys
    p = sys.stdout.write
    print "    # ---------------AUTOGENERATED---------------------"
    
    DT_TPL = \
    """    self.{{name}} = newtype(_s(u"{{name}}"))"""
    CT_TPL = \
    """    self.{{name}} = newctor(_s(u"{{name}}"), self.{{union.name}})"""
    for t in TYPES:
        print render(DT_TPL, t)
        for c in t["ctors"]:
            print render(CT_TPL, c)


def gen_puts():
    print "    # ---------------AUTOGENERATED---------------------"
    def t_put(t):
        return "    api.put(module, types.%s.name, types.%s)" % (t["name"], t["name"])

    for t in TYPES:
        print t_put(t)
        for c in t["ctors"]:
            print t_put(c)

gen_declaration()

gen_puts()