# ************************ LALAN TOKENS*****************************
TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_TICKNAME = 7
TT_OPERATOR = 8
TT_FUN = 9
TT_MATCH = 10
TT_WITH = 11
TT_WITHOUT = 12
TT_CASE = 13
TT_EXTEND = 14
TT_TYPE = 15
TT_IF = 16
TT_ELIF = 17
TT_ELSE = 18
TT_THEN = 19
TT_WHEN = 20
TT_OF = 21
TT_DEF = 22
TT_LET = 23
TT_IN = 24
TT_AS = 25
TT_AND = 26
TT_OR = 27
TT_NOT = 28
TT_TRUE = 29
TT_FALSE = 30
TT_TRY = 31
TT_THROW = 32
TT_CATCH = 33
TT_FINALLY = 34
TT_MODULE = 35
TT_IMPORT = 36
TT_FROM = 37
TT_HIDING = 38
TT_HIDE = 39
TT_EXPORT = 40
TT_TRAIT = 41
TT_PROTOCOL = 42
TT_USE = 43
TT_INTERFACE = 44
TT_END_EXPR = 45
TT_NEWLINE = 46
TT_ELLIPSIS = 47
TT_WILDCARD = 48
TT_GOTO = 49
TT_ARROW = 50
TT_FAT_ARROW = 51
TT_AT_SIGN = 52
TT_SHARP = 53
TT_JUXTAPOSITION = 54
TT_LCURLY = 55
TT_RCURLY = 56
TT_COMMA = 57
TT_ASSIGN = 58
TT_INFIX_DOT_LCURLY = 59
TT_INFIX_DOT_LSQUARE = 60
TT_LPAREN = 61
TT_RPAREN = 62
TT_PREFIX = 63
TT_INFIXL = 64
TT_INFIXR = 65
TT_LSQUARE = 66
TT_RSQUARE = 67
TT_DOT = 68
TT_COLON = 69
TT_DOUBLE_COLON = 70
TT_BACKTICK_NAME = 71
TT_BACKTICK_OPERATOR = 72
TT_UNKNOWN = 73
# ************************ LALAN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_TICKNAME", u"TT_OPERATOR", u"TT_FUN", u"TT_MATCH", u"TT_WITH", u"TT_WITHOUT", u"TT_CASE",
               u"TT_EXTEND", u"TT_TYPE", u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN", u"TT_OF", u"TT_DEF",
               u"TT_LET", u"TT_IN", u"TT_AS", u"TT_AND", u"TT_OR", u"TT_NOT", u"TT_TRUE", u"TT_FALSE", u"TT_TRY",
               u"TT_THROW", u"TT_CATCH", u"TT_FINALLY", u"TT_MODULE", u"TT_IMPORT", u"TT_FROM", u"TT_HIDING",
               u"TT_HIDE", u"TT_EXPORT", u"TT_TRAIT", u"TT_PROTOCOL", u"TT_USE", u"TT_INTERFACE", u"TT_END_EXPR",
               u"TT_NEWLINE", u"TT_ELLIPSIS", u"TT_WILDCARD", u"TT_GOTO", u"TT_ARROW", u"TT_FAT_ARROW", u"TT_AT_SIGN",
               u"TT_SHARP", u"TT_JUXTAPOSITION", u"TT_LCURLY", u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN",
               u"TT_INFIX_DOT_LCURLY", u"TT_INFIX_DOT_LSQUARE", u"TT_LPAREN", u"TT_RPAREN", u"TT_PREFIX", u"TT_INFIXL",
               u"TT_INFIXR", u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON", u"TT_DOUBLE_COLON",
               u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_UNKNOWN", ]


def token_type_to_u(ttype):
    return __TT_REPR__[ttype]


def token_type_to_s(ttype):
    return str(__TT_REPR__[ttype])
