# ************************ LALAN TOKENS*****************************
TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_MULTI_STR = 4
TT_CHAR = 5
TT_NAME = 6
TT_TICKNAME = 7
TT_OPERATOR = 8
TT_FUN = 9
TT_MATCH = 10
TT_WITH = 11
TT_CASE = 12
TT_EXTEND = 13
TT_TYPE = 14
TT_IF = 15
TT_ELIF = 16
TT_ELSE = 17
TT_THEN = 18
TT_WHEN = 19
TT_OF = 20
TT_DEF = 21
TT_LET = 22
TT_IN = 23
TT_AS = 24
TT_AND = 25
TT_OR = 26
TT_NOT = 27
TT_TRUE = 28
TT_FALSE = 29
TT_TRY = 30
TT_THROW = 31
TT_CATCH = 32
TT_FINALLY = 33
TT_MODULE = 34
TT_IMPORT = 35
TT_FROM = 36
TT_HIDING = 37
TT_HIDE = 38
TT_EXPORT = 39
TT_TRAIT = 40
TT_USE = 41
TT_GENERIC = 42
TT_INTERFACE = 43
TT_END_EXPR = 44
TT_NEWLINE = 45
TT_ELLIPSIS = 46
TT_WILDCARD = 47
TT_GOTO = 48
TT_ARROW = 49
TT_FAT_ARROW = 50
TT_AT_SIGN = 51
TT_SHARP = 52
TT_JUXTAPOSITION = 53
TT_LCURLY = 54
TT_RCURLY = 55
TT_COMMA = 56
TT_ASSIGN = 57
TT_INFIX_DOT_LCURLY = 58
TT_INFIX_DOT_LPAREN = 59
TT_INFIX_DOT_LSQUARE = 60
TT_LPAREN = 61
TT_RPAREN = 62
TT_PREFIX = 63
TT_INFIXL = 64
TT_INFIXR = 65
TT_LSQUARE = 66
TT_RSQUARE = 67
TT_DOT = 68
TT_COLON = 69
TT_DOUBLE_COLON = 70
TT_BACKTICK_NAME = 71
TT_BACKTICK_OPERATOR = 72
TT_UNKNOWN = 73
# ************************ LALAN TOKENS REPR *****************************
__TT_REPR__ = [u"TT_ENDSTREAM", u"TT_INT", u"TT_FLOAT", u"TT_STR", u"TT_MULTI_STR", u"TT_CHAR", u"TT_NAME",
               u"TT_TICKNAME", u"TT_OPERATOR", u"TT_FUN", u"TT_MATCH", u"TT_WITH", u"TT_CASE", u"TT_EXTEND", u"TT_TYPE",
               u"TT_IF", u"TT_ELIF", u"TT_ELSE", u"TT_THEN", u"TT_WHEN", u"TT_OF", u"TT_DEF", u"TT_LET", u"TT_IN",
               u"TT_AS", u"TT_AND", u"TT_OR", u"TT_NOT", u"TT_TRUE", u"TT_FALSE", u"TT_TRY", u"TT_THROW", u"TT_CATCH",
               u"TT_FINALLY", u"TT_MODULE", u"TT_IMPORT", u"TT_FROM", u"TT_HIDING", u"TT_HIDE", u"TT_EXPORT",
               u"TT_TRAIT", u"TT_USE", u"TT_GENERIC", u"TT_INTERFACE", u"TT_END_EXPR", u"TT_NEWLINE", u"TT_ELLIPSIS",
               u"TT_WILDCARD", u"TT_GOTO", u"TT_ARROW", u"TT_FAT_ARROW", u"TT_AT_SIGN", u"TT_SHARP",
               u"TT_JUXTAPOSITION", u"TT_LCURLY", u"TT_RCURLY", u"TT_COMMA", u"TT_ASSIGN", u"TT_INFIX_DOT_LCURLY",
               u"TT_INFIX_DOT_LPAREN", u"TT_INFIX_DOT_LSQUARE", u"TT_LPAREN", u"TT_RPAREN", u"TT_PREFIX", u"TT_INFIXL",
               u"TT_INFIXR", u"TT_LSQUARE", u"TT_RSQUARE", u"TT_DOT", u"TT_COLON", u"TT_DOUBLE_COLON",
               u"TT_BACKTICK_NAME", u"TT_BACKTICK_OPERATOR", u"TT_UNKNOWN", ]


def token_type_to_u(ttype):
    return __TT_REPR__[ttype]


def token_type_to_s(ttype):
    return str(__TT_REPR__[ttype])
