class Generics:
    def __init__(self):
        from obin.objects.space import newgeneric, newstring

        ## AUTOGENERATED generic_gen.py
        self.Add = newgeneric(newstring(u"+"))
        self.Sub = newgeneric(newstring(u"-"))
        self.Mul = newgeneric(newstring(u"*"))
        self.Div = newgeneric(newstring(u"/"))
        self.Mod = newgeneric(newstring(u"%"))
        self.UnaryPlus = newgeneric(newstring(u"__unary_plus__"))
        self.UnaryMinus = newgeneric(newstring(u"__unary_minus__"))
        self.Not = newgeneric(newstring(u"not"))
        self.Equal = newgeneric(newstring(u"=="))
        self.NotEqual = newgeneric(newstring(u"!="))
        self.Compare = newgeneric(newstring(u"compare"))
        self.In = newgeneric(newstring(u"contains"))
        self.GreaterThen = newgeneric(newstring(u">"))
        self.GreaterEqual = newgeneric(newstring(u">="))
        self.BitNot = newgeneric(newstring(u"!"))
        self.BitOr = newgeneric(newstring(u"^"))
        self.BitXor = newgeneric(newstring(u"~"))
        self.BitAnd = newgeneric(newstring(u"&"))
        self.LeftShift = newgeneric(newstring(u"<<"))
        self.RightShift = newgeneric(newstring(u">>"))
        self.UnsignedRightShift = newgeneric(newstring(u">>>"))
        self.Length = newgeneric(newstring(u"length"))
        self.Str = newgeneric(newstring(u"str"))


class Traits:
    def __init__(self):
        from obin.objects.space import newtrait, newtraits, newstring
        self.Any = newtrait(newstring(u"Any"))
        self.Boolean = newtrait(newstring(u"Boolean"))

        self.True = newtrait(newstring(u"True"))
        self.TrueTraits = newtraits([self.True, self.Boolean, self.Any])

        self.False = newtrait(newstring(u"False"))
        self.FalseTraits = newtraits([self.False, self.Boolean, self.Any])

        self.Nil = newtrait(newstring(u"Nil"))
        self.NilTraits = newtraits([self.Nil, self.Any])

        self.Undefined = newtrait(newstring(u"Undefined"))
        self.UndefinedTraits = newtraits([self.Undefined, self.Any])

        self.Char = newtrait(newstring(u"Char"))
        self.CharTraits = newtraits([self.Char, self.Any])

        self.Number = newtrait(newstring(u"Number"))
        self.Integer = newtrait(newstring(u"Integer"))
        self.IntegerTraits = newtraits([self.Integer, self.Number, self.Any])

        self.Float = newtrait(newstring(u"Float"))
        self.FloatTraits = newtraits([self.Float, self.Number, self.Any])

        self.Symbol = newtrait(newstring(u"Symbol"))
        self.SymbolTraits = newtraits([self.Symbol, self.Any])

        self.String = newtrait(newstring(u"String"))
        self.StringTraits = newtraits([self.String, self.Any])

        self.List = newtrait(newstring(u"List"))

        self.Vector = newtrait(newstring(u"Vector"))
        self.VectorTraits = newtraits([self.Vector, self.Any])

        self.Tuple = newtrait(newstring(u"Tuple"))
        self.TupleTraits = newtraits([self.Tuple, self.Any])

        self.Function = newtrait(newstring(u"Function"))
        self.FunctionTraits = newtraits([self.Function, self.Any])

        self.Coroutine = newtrait(newstring(u"Coroutine"))
        self.CoroutineTraits = newtraits([self.Coroutine, self.Function, self.Any])

        self.Generic = newtrait(newstring(u"Generic"))
        self.GenericTraits = newtraits([self.Generic, self.Function, self.Any])

        self.Primitive = newtrait(newstring(u"Primitive"))
        self.PrimitiveTraits = newtraits([self.Primitive, self.Function, self.Any])

        self.Object = newtrait(newstring(u"Object"))
        self.ObjectTraits = newtraits([self.Object, self.Any])

        self.Module = newtrait(newstring(u"Object"))
        self.ModuleTraits = newtraits([self.Module, self.Any])


class StdLib:
    def __init__(self):
        self.traits = Traits()
        self.generics = Generics()


