LOAD_LIST = 0
NEXT_ITERATOR = 1
LOAD_MEMBER_DOT = 2
JUMP_IF_ITERATOR_EMPTY = 3
LOAD_LOCAL = 4
LABEL = 5
LOAD_OUTER = 6
LOAD_VECTOR = 7
STORE_MEMBER = 8
LOAD_MEMBER = 9
LOAD_OBJECT = 10
CALL = 11
LOAD_FUNCTION = 12
LOAD_ITERATOR = 13
CALL_METHOD = 14
JUMP_IF_FALSE_NOPOP = 15
JUMP_IF_TRUE_NOPOP = 16
JUMP_IF_FALSE = 17
DUP = 18
POP = 19
RETURN = 20
LOAD_NULL = 21
LOAD_UNDEFINED = 22
JUMP_IF_TRUE = 23
CALL_PRIMITIVE = 24
THROW = 25
LOAD_TRUE = 26
LOAD_FALSE = 27
LOAD_LITERAL = 28
JUMP = 29
STORE_OUTER = 30
STORE_LOCAL = 31
__LENGTH__ = 32

# ************************************************

__REPR__ = [None] * __LENGTH__
__REPR__[LOAD_LIST] = "LOAD_LIST"
__REPR__[NEXT_ITERATOR] = "NEXT_ITERATOR"
__REPR__[LOAD_MEMBER_DOT] = "LOAD_MEMBER_DOT"
__REPR__[JUMP_IF_ITERATOR_EMPTY] = "JUMP_IF_ITERATOR_EMPTY"
__REPR__[LOAD_LOCAL] = "LOAD_LOCAL"
__REPR__[LABEL] = "LABEL"
__REPR__[LOAD_OUTER] = "LOAD_OUTER"
__REPR__[LOAD_VECTOR] = "LOAD_VECTOR"
__REPR__[STORE_MEMBER] = "STORE_MEMBER"
__REPR__[LOAD_MEMBER] = "LOAD_MEMBER"
__REPR__[LOAD_OBJECT] = "LOAD_OBJECT"
__REPR__[CALL] = "CALL"
__REPR__[LOAD_FUNCTION] = "LOAD_FUNCTION"
__REPR__[LOAD_ITERATOR] = "LOAD_ITERATOR"
__REPR__[CALL_METHOD] = "CALL_METHOD"
__REPR__[JUMP_IF_FALSE_NOPOP] = "JUMP_IF_FALSE_NOPOP"
__REPR__[JUMP_IF_TRUE_NOPOP] = "JUMP_IF_TRUE_NOPOP"
__REPR__[JUMP_IF_FALSE] = "JUMP_IF_FALSE"
__REPR__[DUP] = "DUP"
__REPR__[POP] = "POP"
__REPR__[RETURN] = "RETURN"
__REPR__[LOAD_NULL] = "LOAD_NULL"
__REPR__[LOAD_UNDEFINED] = "LOAD_UNDEFINED"
__REPR__[JUMP_IF_TRUE] = "JUMP_IF_TRUE"
__REPR__[CALL_PRIMITIVE] = "CALL_PRIMITIVE"
__REPR__[THROW] = "THROW"
__REPR__[LOAD_TRUE] = "LOAD_TRUE"
__REPR__[LOAD_FALSE] = "LOAD_FALSE"
__REPR__[LOAD_LITERAL] = "LOAD_LITERAL"
__REPR__[JUMP] = "JUMP"
__REPR__[STORE_OUTER] = "STORE_OUTER"
__REPR__[STORE_LOCAL] = "STORE_LOCAL"

# ************************************************

def opcode_to_str(p):
    return __REPR__[p]



