from obin.types import api, space, symbol


def presetup(process, module, stdlib):
    import obin.builtins.lang
    obin.builtins.lang.setup(process, module, stdlib)

    # MODULES
    import obin.builtins.modules.module_core_types
    obin.builtins.modules.module_core_types.setup(process, stdlib)

    import obin.builtins.modules.module_list
    obin.builtins.modules.module_list.setup(process, stdlib)

    import obin.builtins.modules.module_tuple
    obin.builtins.modules.module_tuple.setup(process, stdlib)

    import obin.builtins.modules.module_coro
    obin.builtins.modules.module_coro.setup(process, stdlib)

    import obin.builtins.modules.module_bit
    obin.builtins.modules.module_bit.setup(process, stdlib)

    import obin.builtins.modules.module_io
    obin.builtins.modules.module_io.setup(process, stdlib)

    import obin.builtins.modules.module_api
    obin.builtins.modules.module_api.setup(process, stdlib)

    import obin.builtins.modules.module_number
    obin.builtins.modules.module_number.setup(process, stdlib)

    import obin.builtins.modules.module_string
    obin.builtins.modules.module_string.setup(process, stdlib)

    import obin.builtins.modules.module_map
    obin.builtins.modules.module_map.setup(process, stdlib)

    import obin.builtins.modules.module_datatype
    obin.builtins.modules.module_datatype.setup(process, stdlib)

    import obin.builtins.modules.module_lazy
    obin.builtins.modules.module_lazy.setup(process, stdlib)

    module.export_all()


def postsetup(process):
    setup_hotpath(process)
    create_lang_names(process)


def create_lang_names(process):
    from obin.builtins import lang_names
    prelude = process.modules.prelude
    exports = prelude.exports()
    lang_prefix = space.newsymbol_s(process, lang_names.PREFIX)
    for name in exports:
        new_name = symbol.concat_2(process, lang_prefix, name)
        val = api.at(prelude, name)
        api.put(prelude, new_name, val)


def setup_hotpath(process):
    from obin.builtins import hotpath as hp
    prelude = process.modules.prelude

    def _s(ustr):
        return space.newsymbol(process, ustr)

    # ---------------AUTOGENERATED---------------------
    api.at(prelude, _s(u"==")).set_hotpath(hp.hp_eq)

    api.at(prelude, _s(u"!=")).set_hotpath(hp.hp_ne)

    api.at(prelude, _s(u"str")).set_hotpath(hp.hp_str)

    api.at(prelude, _s(u"<=")).set_hotpath(hp.hp_le)

    api.at(prelude, _s(u"negate")).set_hotpath(hp.hp_uminus)

    api.at(prelude, _s(u"+")).set_hotpath(hp.hp_add)

    api.at(prelude, _s(u"-")).set_hotpath(hp.hp_sub)

    api.at(prelude, _s(u"*")).set_hotpath(hp.hp_mul)

    api.at(prelude, _s(u"/")).set_hotpath(hp.hp_div)

    api.at(prelude, _s(u"mod")).set_hotpath(hp.hp_mod)

    # collection
    api.at(prelude, _s(u"elem")).set_hotpath(hp.hp_elem)

    api.at(prelude, _s(u"at")).set_hotpath(hp.hp_at)

    api.at(prelude, _s(u"put")).set_hotpath(hp.hp_put)

    api.at(prelude, _s(u"len")).set_hotpath(hp.hp_len)

    # appendable
    api.at(prelude, _s(u"++")).set_hotpath(hp.hp_concat)

    # seq
    api.at(prelude, _s(u"cons")).set_hotpath(hp.hp_cons)

    api.at(prelude, _s(u"first")).set_hotpath(hp.hp_first)

    api.at(prelude, _s(u"rest")).set_hotpath(hp.hp_rest)

    api.at(prelude, _s(u"slice")).set_hotpath(hp.hp_slice)

    api.at(prelude, _s(u"take")).set_hotpath(hp.hp_take)

    api.at(prelude, _s(u"drop")).set_hotpath(hp.hp_drop)

    api.at(prelude, _s(u"is_empty")).set_hotpath(hp.hp_is_empty)
