# ************************ OBIN TOKENS*****************************
TT_ENDSTREAM = 0
TT_INT = 1
TT_FLOAT = 2
TT_STR = 3
TT_CHAR = 4
TT_NAME = 5
TT_NEWLINE = 6
TT_BREAK = 7
TT_CASE = 8
TT_CONTINUE = 9
TT_ELSE = 10
TT_FOR = 11
TT_WHILE = 12
TT_IF = 13
TT_WHEN = 14
TT_ELIF = 15
TT_OF = 16
TT_AS = 17
TT_MATCH = 18
TT_FUNC = 19
TT_AND = 20
TT_OR = 21
TT_NOT = 22
TT_TRUE = 23
TT_FALSE = 24
TT_NIL = 25
TT_UNDEFINED = 26
TT_THROW = 27
TT_CATCH = 28
TT_IN = 29
TT_IS = 30
TT_ORIGIN = 31
TT_ISNOT = 32
TT_OUTER = 33
TT_FROM = 34
TT_IMPORT = 35
TT_TRAIT = 36
TT_GENERIC = 37
TT_SPECIFY = 38
TT_END = 39
TT_RETURN = 40
TT_ELLIPSIS = 41
TT_ADD_ASSIGN = 42
TT_SUB_ASSIGN = 43
TT_MUL_ASSIGN = 44
TT_DIV_ASSIGN = 45
TT_MOD_ASSIGN = 46
TT_BITAND_ASSIGN = 47
TT_BITXOR_ASSIGN = 48
TT_BITOR_ASSIGN = 49
TT_WILDCARD = 50
TT_GOTO = 51
TT_RSHIFT = 52
TT_URSHIFT = 53
TT_LSHIFT = 54
TT_ARROW = 55
TT_FAT_ARROW = 56
TT_EQ = 57
TT_LE = 58
TT_GE = 59
TT_NE = 60
TT_SEMI = 61
TT_COLON = 62
TT_DOUBLE_COLON = 63
TT_LCURLY = 64
TT_RCURLY = 65
TT_COMMA = 66
TT_ASSIGN = 67
TT_LPAREN = 68
TT_RPAREN = 69
TT_LSQUARE = 70
TT_RSQUARE = 71
TT_DOT = 72
TT_BITAND = 73
TT_BITNOT = 74
TT_BITOR = 75
TT_BITXOR = 76
TT_SUB = 77
TT_ADD = 78
TT_MUL = 79
TT_DIV = 80
TT_BACKTICK = 81
TT_MOD = 82
TT_LT = 83
TT_GT = 84
TT_UNKNOWN = 85
# ************************ OBIN TOKENS REPR *****************************
__TT_REPR__ = ["TT_ENDSTREAM", "TT_INT", "TT_FLOAT", "TT_STR", "TT_CHAR", "TT_NAME", "TT_NEWLINE", "TT_BREAK",
               "TT_CASE", "TT_CONTINUE", "TT_ELSE", "TT_FOR", "TT_WHILE", "TT_IF", "TT_WHEN", "TT_ELIF", "TT_OF",
               "TT_AS", "TT_MATCH", "TT_FUNC", "TT_AND", "TT_OR", "TT_NOT", "TT_TRUE", "TT_FALSE", "TT_NIL",
               "TT_UNDEFINED", "TT_THROW", "TT_CATCH", "TT_IN", "TT_IS", "TT_ORIGIN", "TT_ISNOT", "TT_OUTER", "TT_FROM",
               "TT_IMPORT", "TT_TRAIT", "TT_GENERIC", "TT_SPECIFY", "TT_END", "TT_RETURN", "TT_ELLIPSIS",
               "TT_ADD_ASSIGN", "TT_SUB_ASSIGN", "TT_MUL_ASSIGN", "TT_DIV_ASSIGN", "TT_MOD_ASSIGN", "TT_BITAND_ASSIGN",
               "TT_BITXOR_ASSIGN", "TT_BITOR_ASSIGN", "TT_WILDCARD", "TT_GOTO", "TT_RSHIFT", "TT_URSHIFT", "TT_LSHIFT",
               "TT_ARROW", "TT_FAT_ARROW", "TT_EQ", "TT_LE", "TT_GE", "TT_NE", "TT_SEMI", "TT_COLON", "TT_DOUBLE_COLON",
               "TT_LCURLY", "TT_RCURLY", "TT_COMMA", "TT_ASSIGN", "TT_LPAREN", "TT_RPAREN", "TT_LSQUARE", "TT_RSQUARE",
               "TT_DOT", "TT_BITAND", "TT_BITNOT", "TT_BITOR", "TT_BITXOR", "TT_SUB", "TT_ADD", "TT_MUL", "TT_DIV",
               "TT_BACKTICK", "TT_MOD", "TT_LT", "TT_GT", "TT_UNKNOWN", ]


def token_type_to_str(ttype):
    return __TT_REPR__[ttype]
