from arza.types import api, space, symbol


def presetup(process, module, stdlib):
    import arza.builtins.lang

    arza.builtins.lang.setup(process, module, stdlib)

    import arza.builtins.classes.setup_object
    arza.builtins.classes.setup_object.setup(process, stdlib)

    import arza.builtins.classes.setup_class
    arza.builtins.classes.setup_class.setup(process, stdlib)
    setup_classes(module, stdlib.classes)

    module.export_all()


def setup_classes(module, classes):
    # ---------------AUTOGENERATED---------------------
    api.put(module, classes.Bool.name, classes.Bool)
    api.put(module, classes.Char.name, classes.Char)
    api.put(module, classes.Int.name, classes.Int)
    api.put(module, classes.Float.name, classes.Float)
    api.put(module, classes.Symbol.name, classes.Symbol)
    api.put(module, classes.String.name, classes.String)
    api.put(module, classes.List.name, classes.List)
    api.put(module, classes.Vector.name, classes.Vector)
    api.put(module, classes.Tuple.name, classes.Tuple)
    api.put(module, classes.Dict.name, classes.Dict)
    api.put(module, classes.Function.name, classes.Function)
    api.put(module, classes.FiberChannel.name, classes.FiberChannel)
    api.put(module, classes.Coroutine.name, classes.Coroutine)
    api.put(module, classes.Object.name, classes.Object)
    api.put(module, classes.Class.name, classes.Class)
    api.put(module, classes.Env.name, classes.Env)
    api.put(module, classes.Array.name, classes.Array)
    api.put(module, classes.PID.name, classes.PID)


def postsetup(process):
    create_lang_names(process)


def create_lang_names(process):
    from arza.builtins import lang_names
    prelude = process.classes.prelude
    exports = prelude.exports()
    lang_prefix = space.newsymbol_s(process, lang_names.PREFIX)
    for name in exports:
        new_name = symbol.concat_2(process, lang_prefix, name)
        val = api.at(prelude, name)
        api.put(prelude, new_name, val)
